// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSZfnU17XSMuu2XeGYD0bkHhHpXlKDxzY',
    appId: '1:175708275752:web:9d3647b267fad54104611d',
    messagingSenderId: '175708275752',
    projectId: 'aaz-servicos',
    authDomain: 'aaz-servicos.firebaseapp.com',
    storageBucket: 'aaz-servicos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF53mBVWo4i0OX3zl1JQbQO5HmxUdCUAA',
    appId: '1:175708275752:android:8472efb36926205304611d',
    messagingSenderId: '175708275752',
    projectId: 'aaz-servicos',
    storageBucket: 'aaz-servicos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS-M_8qtdSAzgYDIzulDh0kqxEq0oWjDs',
    appId: '1:175708275752:ios:c9c42e4d81cce04b04611d',
    messagingSenderId: '175708275752',
    projectId: 'aaz-servicos',
    storageBucket: 'aaz-servicos.appspot.com',
    iosBundleId: 'com.example.aazServicos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS-M_8qtdSAzgYDIzulDh0kqxEq0oWjDs',
    appId: '1:175708275752:ios:7605b5ad4ccf225004611d',
    messagingSenderId: '175708275752',
    projectId: 'aaz-servicos',
    storageBucket: 'aaz-servicos.appspot.com',
    iosBundleId: 'com.example.aazServicos.RunnerTests',
  );
}
